// GENERATED from tokens.json — ne pas éditer
#ifndef WAVE_TOKENS_H
#define WAVE_TOKENS_H
#define WVP_SPRING_MORPH_K 400f
#define WVP_SPRING_MORPH_D 28f
#define WVP_SPRING_MORPH_M 0.85f
#define WVP_SPRING_SHADE_K 350f
#define WVP_SPRING_SHADE_D 30f
#define WVP_SPRING_SHADE_M 0.8f
#define WVP_SPRING_ISLAND_K 400f
#define WVP_SPRING_ISLAND_D 30f
#define WVP_SPRING_ISLAND_M 1f
#define WVP_SPRING_SNAP_K 500f
#define WVP_SPRING_SNAP_D 34f
#define WVP_SPRING_SNAP_M 1f
#define WVP_SPRING_PILL_K 220f
#define WVP_SPRING_PILL_D 24f
#define WVP_SPRING_PILL_M 1f
#define WVP_RUBBER 0.2f
#define WVP_SCREEN_W 400
#define WVP_SCREEN_H 850
#endif
